
#define ROOM_MAX 1000
#define ROOM_NAME_MAX_LEN 100
#define ROOM_HISTORY_LEN 5
#define ROOM_USER_MAX 10
#define ROOM_STATUS_OFF 0 
#define ROOM_STATUS_ON 1

#define USER_MAX 1000
#define USER_NAME_MAX_LEN 100
#define USER_STATUS_ONLINE 1
#define USER_STATUS_OFFLINE 0

#define LOG_MAX_LEN 100